kind: Deployment
apiVersion: apps/v1
metadata:
  name: will42-playground
spec:
  selector:
    matchLabels:
      app: will42
  replicas: 1
  template:
    metadata:
      labels:
        app: will42
    spec:
      containers:
        - name: will42
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: will42
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: will42