kind: Deployment
apiVersion: apps/v1
metadata:
  name: will42-playground
spec:
  selector:
    matchLabels:
      app: will42
  replicas: 1
  template:
    metadata:
      labels:
        app: will42
    spec:
      containers:
        - name: will42
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: will42
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: will42

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: will42-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: will42
                port:
                  number: 8888